---

- name: Example of how to provision VMs (all in one data structure)
  hosts: all
  connection: local
  gather_facts: no
  vars:
    # List of VMs to provision
    vmware_vm_provisioning_vms:
      # Fist VM
      - name: test01
        hostname: demo-vcenter.zones-lab.com
        username: Administrator@vsphere.local
        password: DemoAdmin1!
        validate_certs: no
        datacenter: Demo Center
        cluster: ESX Cluster
        folder: /DC1/vm
        template: LinuxTmp
        disks:
          - size_gb: 20
            autoselect_datastore: yes
        network:
          - name: Demo-Switch-Management Network
            ip: 172.30.1.151
            netmask: 255.255.255.0
            gateway: 172.30.1.1
        hadrware:
          num_cpus: 2
          memory_mb: 2048
     
        state: rebuilt
  roles:
    - role: vmware_vm_provisioning
      tags: vmware_vm_provisioning
      when: >
        inventory_hostname == 'localhost'
